os: linux
dist: trusty
language: java

jdk:
  - openjdk16

# Run before every job
before_install:
  - java -version
  - uname -a
  - chmod +x pom.xml

# Only running report_coverage (after merge) to master branch
stages:
  - test
  - name: report_coverage
    if: branch = main AND type != pull_request

# List of jobs to run, tied to specific stages
jobs:
  include:
    - stage: test
      name: UnitTests
      script:
        #- mvn test
        - java --version
        - jdk_switcher use oraclejdk8
        - java --version
        - which java
        - ECHO $PATH
        - ECHO $JAVA_HOME
    - stage: report_coverage
      name: report_coverage
      # Generating test coverage report and publishing to Codacy
      script:
        - mvn clean test jacoco:report
        - curl -Ls -o codacy-coverage-reporter-assembly.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/12.2.0/codacy-coverage-reporter-assembly.jar
        - jdk_switcher use oraclejdk8
        - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml
