name: Java CI with JaCoCo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean verify

#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        file: ./target/site/jacoco/jacoco.xml
#        flags: unittests
#        name: codecov-umbrella
#        fail_ci_if_error: true